### ISSUE TITLE
Thoughts on "angular-interview-questions-for-seniors"

### ISSUE THREAD

**Issue by GregOnNet** [brechtbilliet/brechtbilliet.github.io#12]
[Related Post](https://github.com/brechtbilliet/brechtbilliet.github.io/blob/master/_posts/2022-08-10-angular-interview-questions-for-seniors.md)

Hi,

in this issue, I collect my thoughts on your article.
I like the article and the details you provide. 👍

## Open Questions

Asking open questions defers from my interview style, but I really like your approach.
E.g. I go more into detail when it comes to RxJS. I want to know what the candidate already did in previous projects. Furthermore, I expect that a Senior Angular Developer knows about higher order observables.

Other than that, I am excited to hear how my interview partner thinks about Clean Code and SOLID & how she or he applies these concepts in Angular.

Sometimes I let the candidate review a piece of code of our project to check the Code-Review capabilities as well.

## Comments on specific paragraphs

Questions like that could make our candidate uncomfortable and stressed out. I also don't like to ask:
> What's the difference between `markForCheck()` and `detectChanges()`?

Personally, I want to see how my interview partner reacts to a stressful situation.
Stress is subjective. I am totally fine when someone does not have the correct answer in mind.
Asking a complicated question can tell a lot about the personality of your interview partner.

---

>  Everyone can memorize api's...

I made other experiences here. Often a candidate thinks/claims to know Angular very well, but asking a simple questions reveals they don't.
That's why I ask a few, short API-questions. If I see that the candidate understands the APIs, I move on with other questions.

**Comment by brechtbilliet** [comment]
Thanks for your review! First of all the article is very specific to Angular. RxJS questions will be covered in a next article.
The same goes for clean code and SOLID. That would be in the architecture quesitons.
Thanks for your feedback, I value it a lot
